'use client'

import Link from 'next/link'
import { useState } from 'react'
import { useSpendGuardStore } from '@/lib/store/use-spendguard-store'
import type { PlanBenefits } from '@/lib/types'
import { currency, daysUntil, getPlansForItem, getRenewalForItem, getSnapshotsForItem, latestPlanPair, percentChange, shortDate } from '@/lib/services'
import { EmptyState, PageIntro, Panel, StatusBadge } from '@/components/dashboard/product-ui'

function PriceHistory({ itemId }: { itemId: string }) {
  const { data } = useSpendGuardStore()
  const snapshots = getSnapshotsForItem(data, itemId)
  if (!snapshots.length) return <EmptyState title="No price history yet" description="SpendGuard will show a trend after it captures the next price check." />
  const max = Math.max(...snapshots.map((snapshot) => snapshot.price))
  const min = Math.min(...snapshots.map((snapshot) => snapshot.price))
  const range = Math.max(max - min, 1)
  return <div className="mt-6"><div className="flex h-48 items-end gap-3 border-b border-l border-[var(--border)] px-3">{snapshots.map((snapshot) => <div key={snapshot.id} className="group relative flex h-full flex-1 items-end"><div className="w-full rounded-t-lg bg-[var(--powder)] transition group-hover:bg-[var(--accent)]" style={{ height: `${Math.max(((snapshot.price - min) / range) * 75 + 25, 28)}%` }}><span className="absolute -top-7 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded-md bg-[var(--surface-dark)] px-1.5 py-1 text-[10px] font-bold text-white group-hover:block">{currency(snapshot.price)}</span></div></div>)}</div><div className="mt-3 flex justify-between gap-3 text-xs text-[var(--foreground-muted)]"><span>{shortDate(snapshots[0].capturedAt)}</span><span>{shortDate(snapshots[snapshots.length - 1].capturedAt)}</span></div></div>
}

function ClaimModal({ itemId, onClose }: { itemId: string; onClose: () => void }) {
  const { data } = useSpendGuardStore()
  const purchase = data.items.find((item) => item.id === itemId)?.purchase
  const [copied, setCopied] = useState(false)
  if (!purchase) return null
  const message = `Hello, I purchased ${purchase.product} on ${shortDate(purchase.purchaseDate)} for ${currency(purchase.paidPrice)} (order ${purchase.orderNumber ?? 'N/A'}). The current price is ${currency(purchase.currentPrice)}. Could you please let me know whether a price adjustment is available?`
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(message)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 1800)
    } catch {
      setCopied(false)
    }
  }
  return <div role="dialog" aria-modal="true" aria-labelledby="claim-title" className="fixed inset-0 z-50 grid place-items-center bg-[#0c0f14]/40 p-4"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-[20px] bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--accent)]">PriceClaim guidance</p><h3 id="claim-title" className="mt-2 font-display text-2xl font-extrabold tracking-[-0.04em]">Ask for a price adjustment</h3></div><button type="button" aria-label="Close claim instructions" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl text-xl hover:bg-[var(--surface-subtle)]">×</button></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[var(--surface-subtle)] p-3"><p className="text-xs text-[var(--foreground-muted)]">Potential claim</p><p className="mt-1 text-lg font-extrabold text-[var(--success)]">{currency(purchase.claimAmount)}</p></div><div className="rounded-xl bg-[var(--surface-subtle)] p-3"><p className="text-xs text-[var(--foreground-muted)]">Retailer</p><p className="mt-1 text-sm font-bold">{purchase.retailer}</p></div><div className="rounded-xl bg-[var(--surface-subtle)] p-3"><p className="text-xs text-[var(--foreground-muted)]">Window</p><p className="mt-1 text-sm font-bold">{purchase.claimDaysRemaining ?? '—'} days</p></div></div><ol className="mt-6 space-y-3 text-sm leading-6 text-[var(--foreground-secondary)]"><li><span className="mr-2 font-bold text-[var(--foreground)]">1.</span>Open your order details at {purchase.retailer}.</li><li><span className="mr-2 font-bold text-[var(--foreground)]">2.</span>Use the support or price-adjustment contact method before the window closes.</li><li><span className="mr-2 font-bold text-[var(--foreground)]">3.</span>Send the prepared message below and attach your order details if requested.</li></ol><div className="mt-6"><div className="mb-2 flex items-center justify-between gap-3"><p className="text-sm font-bold">Sample support message</p><button type="button" onClick={copy} className="text-xs font-bold text-[var(--accent)] hover:underline">{copied ? 'Copied' : 'Copy text'}</button></div><textarea readOnly value={message} className="min-h-32 w-full resize-y rounded-xl border border-[var(--border)] bg-[var(--surface-subtle)] p-3 text-sm leading-6 text-[var(--foreground-secondary)] outline-none" /></div><p className="mt-5 rounded-xl bg-[var(--warning-soft)] px-4 py-3 text-xs leading-5 text-[var(--warning)]"><strong>Manual action required.</strong> SpendGuard does not submit claims or request refunds automatically.</p></div></div>
}

const planFields = ['storage', 'users', 'exports', 'aiCredits', 'projects', 'other'] as const satisfies readonly (keyof PlanBenefits)[]

export function ItemDetail({ itemId }: { itemId: string }) {
  const { data, updateSubscriptionStatus } = useSpendGuardStore()
  const [claimOpen, setClaimOpen] = useState(false)
  const item = data.items.find((entry) => entry.id === itemId)
  if (!item) return <EmptyState title="Item not found" description="This item may have been removed, or the link is out of date." action={<Link href="/app" className="inline-flex min-h-11 items-center rounded-xl bg-[var(--accent)] px-4 text-sm font-bold text-white">Back to overview</Link>} />

  const purchase = item.purchase
  const subscription = item.subscription
  const plans = subscription ? latestPlanPair(getPlansForItem(data, itemId)) : { original: undefined, current: undefined }
  const renewal = subscription ? getRenewalForItem(data, itemId) : undefined
  const change = subscription && subscription.originalPrice ? percentChange(subscription.originalPrice, subscription.currentPrice) : 0
  const title = item.type === 'purchase' ? 'PriceClaim' : 'PlanGuard + RenewalAudit'

  return <>
    <PageIntro eyebrow={title} title={item.title} description={item.subtitle} action={<Link href={item.type === 'purchase' ? '/app/purchases' : '/app/subscriptions'} className="text-sm font-bold text-[var(--accent)] hover:underline">← Back to list</Link>} />
    {purchase ? <div className="space-y-5">
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Panel className="p-5"><p className="text-sm text-[var(--foreground-secondary)]">You paid</p><p className="mt-2 font-display text-2xl font-extrabold">{currency(purchase.paidPrice)}</p><p className="mt-1 text-xs text-[var(--foreground-muted)]">{shortDate(purchase.purchaseDate)}</p></Panel><Panel className="p-5"><p className="text-sm text-[var(--foreground-secondary)]">Current price</p><p className="mt-2 font-display text-2xl font-extrabold">{currency(purchase.currentPrice)}</p><p className="mt-1 text-xs text-[var(--success)]">{purchase.claimAmount ? `${currency(purchase.claimAmount)} lower` : 'No change found'}</p></Panel><Panel className="p-5"><p className="text-sm text-[var(--foreground-secondary)]">Potential claim</p><p className="mt-2 font-display text-2xl font-extrabold text-[var(--success)]">{currency(purchase.claimAmount)}</p><p className="mt-1 text-xs text-[var(--foreground-muted)]">Manual request only</p></Panel><Panel className="p-5"><p className="text-sm text-[var(--foreground-secondary)]">Claim window</p><p className="mt-2 font-display text-2xl font-extrabold">{purchase.claimDaysRemaining ? `${purchase.claimDaysRemaining} days` : 'Watching'}</p><p className="mt-1 text-xs text-[var(--foreground-muted)]">{purchase.claimDeadline ? `Until ${shortDate(purchase.claimDeadline)}` : 'No active deadline'}</p></Panel></div>
      <div className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><Panel><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold">Price history</p><p className="mt-1 text-xs text-[var(--foreground-muted)]">Captured snapshots for this item</p></div><StatusBadge tone={purchase.claimAmount > 0 ? 'success' : 'neutral'}>{purchase.claimAmount > 0 ? 'Price drop found' : 'Monitoring'}</StatusBadge></div><PriceHistory itemId={item.id} /></Panel><Panel><p className="text-sm font-bold">Purchase details</p><dl className="mt-5 divide-y divide-[var(--border)] text-sm"><div className="flex justify-between gap-3 py-3 first:pt-0"><dt className="text-[var(--foreground-secondary)]">Retailer</dt><dd className="font-semibold">{purchase.retailer}</dd></div><div className="flex justify-between gap-3 py-3"><dt className="text-[var(--foreground-secondary)]">Order number</dt><dd className="font-semibold">{purchase.orderNumber ?? 'Not added'}</dd></div><div className="flex justify-between gap-3 py-3"><dt className="text-[var(--foreground-secondary)]">Purchased</dt><dd className="font-semibold">{shortDate(purchase.purchaseDate)}</dd></div><div className="flex justify-between gap-3 py-3 last:pb-0"><dt className="text-[var(--foreground-secondary)]">Source</dt><dd className="font-semibold">{purchase.url ? <a href={purchase.url} target="_blank" rel="noreferrer" className="text-[var(--accent)] hover:underline">Open link</a> : 'Manual entry'}</dd></div></dl><button type="button" disabled={!purchase.claimAmount} onClick={() => setClaimOpen(true)} className="mt-6 min-h-12 w-full rounded-xl bg-[var(--surface-dark)] px-4 text-sm font-bold text-white transition hover:bg-[#1c2a40] disabled:cursor-not-allowed disabled:opacity-40">{purchase.claimAmount ? 'View claim instructions' : 'No claim available yet'}</button></Panel></div>
    </div> : subscription ? <div className="space-y-5">
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Panel className="p-5"><p className="text-sm text-[var(--foreground-secondary)]">Current price</p><p className="mt-2 font-display text-2xl font-extrabold">{currency(subscription.currentPrice)}<span className="font-sans text-sm font-semibold text-[var(--foreground-muted)]">/{subscription.billingCycle === 'annual' ? 'yr' : 'mo'}</span></p><p className="mt-1 text-xs text-[var(--foreground-muted)]">{subscription.plan}</p></Panel><Panel className="p-5"><p className="text-sm text-[var(--foreground-secondary)]">Original price</p><p className="mt-2 font-display text-2xl font-extrabold">{currency(subscription.originalPrice)}</p><p className={`mt-1 text-xs font-bold ${change > 0 ? 'text-[var(--warning)]' : 'text-[var(--success)]'}`}>{change > 0 ? `+${change.toFixed(1)}% change` : 'No price change'}</p></Panel><Panel className="p-5"><p className="text-sm text-[var(--foreground-secondary)]">Annual impact</p><p className="mt-2 font-display text-2xl font-extrabold">{subscription.annualImpact ? `+${currency(subscription.annualImpact)}` : currency(0)}</p><p className="mt-1 text-xs text-[var(--foreground-muted)]">Compared with your baseline</p></Panel><Panel className="p-5"><p className="text-sm text-[var(--foreground-secondary)]">Next renewal</p><p className="mt-2 font-display text-2xl font-extrabold">{daysUntil(subscription.nextRenewal)} days</p><p className="mt-1 text-xs text-[var(--foreground-muted)]">{shortDate(subscription.nextRenewal)}</p></Panel></div>
      <Panel><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold">Original plan vs current plan</p><p className="mt-1 text-xs text-[var(--foreground-muted)]">Changes are described in words as well as status colour.</p></div><StatusBadge tone={subscription.status === 'stable' ? 'success' : subscription.status === 'renewing_soon' ? 'warning' : 'accent'}>{subscription.status === 'stable' ? 'Stable' : subscription.status === 'renewing_soon' ? 'Renewal soon' : subscription.status === 'price_increase' ? 'Price increased' : 'Plan changed'}</StatusBadge></div><div className="mt-6 overflow-x-auto"><div className="min-w-[560px] rounded-xl border border-[var(--border)]"><div className="grid grid-cols-[1.1fr_1fr_1fr] border-b border-[var(--border)] bg-[var(--surface-subtle)] text-xs font-bold uppercase tracking-[0.1em] text-[var(--foreground-muted)]"><div className="p-4">Feature</div><div className="border-l border-[var(--border)] p-4">Original</div><div className="border-l border-[var(--border)] p-4">Current</div></div><div className="divide-y divide-[var(--border)]">{['price', ...planFields].map((field) => { const original = field === 'price' ? plans.original?.price ? currency(plans.original.price) : '—' : plans.original?.benefits[field] ?? '—'; const current = field === 'price' ? plans.current?.price ? currency(plans.current.price) : '—' : plans.current?.benefits[field] ?? '—'; const changed = original !== current; return <div key={field} className="grid grid-cols-[1.1fr_1fr_1fr] text-sm"><div className="p-4 font-bold capitalize">{field === 'aiCredits' ? 'AI credits' : field}</div><div className="border-l border-[var(--border)] p-4 text-[var(--foreground-secondary)]">{original}</div><div className={`border-l border-[var(--border)] p-4 font-semibold ${changed ? 'bg-[var(--warning-soft)] text-[var(--warning)]' : ''}`}>{current}{changed && <span className="ml-2 text-xs">Changed</span>}</div></div> })}</div></div></div></Panel>
      <Panel><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold">Renewal review</p><p className="mt-1 text-xs text-[var(--foreground-muted)]">Make a decision before the next charge.</p></div>{renewal && <StatusBadge tone={daysUntil(renewal.date) <= 14 ? 'warning' : 'neutral'}>{daysUntil(renewal.date)} days left</StatusBadge>}</div>{renewal && <div className="mt-5 grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-[var(--surface-subtle)] p-4"><p className="text-xs text-[var(--foreground-muted)]">Renews</p><p className="mt-1 text-lg font-bold">{shortDate(renewal.date)}</p></div><div className="rounded-xl bg-[var(--surface-subtle)] p-4"><p className="text-xs text-[var(--foreground-muted)]">Upcoming price</p><p className="mt-1 text-lg font-bold">{currency(renewal.upcomingPrice)}</p></div><div className="rounded-xl bg-[var(--surface-subtle)] p-4"><p className="text-xs text-[var(--foreground-muted)]">Annual difference</p><p className="mt-1 text-lg font-bold text-[var(--warning)]">{renewal.upcomingPrice > renewal.previousPrice ? `+${currency((renewal.upcomingPrice - renewal.previousPrice) * 12)}` : currency(0)}</p></div></div>}<div className="mt-6 flex flex-wrap gap-2"><button type="button" onClick={() => updateSubscriptionStatus(item.id, 'stable')} className="min-h-11 rounded-xl border border-[var(--border)] px-4 text-sm font-bold hover:bg-[var(--surface-subtle)]">Keep watching</button><button type="button" onClick={() => updateSubscriptionStatus(item.id, 'renewing_soon')} className="min-h-11 rounded-xl bg-[var(--accent)] px-4 text-sm font-bold text-white hover:bg-[var(--accent-hover)]">Mark for review</button><button type="button" onClick={() => updateSubscriptionStatus(item.id, 'cancelled')} className="min-h-11 rounded-xl px-4 text-sm font-bold text-[var(--danger)] hover:bg-[var(--danger-soft)]">Mark cancelled</button></div></Panel>
    </div> : null}
    {claimOpen && <ClaimModal itemId={item.id} onClose={() => setClaimOpen(false)} />}
  </>
}
