import { ButtonLink, Eyebrow, FaqAccordion, Reveal, SectionIntro } from '@/components/marketing/marketing-ui'
import { MonitorPreview, SavingsChart } from '@/components/marketing/product-preview'
import { faqItems, productSignals, resources, valueStrip } from '@/components/marketing/marketing-data'

export default function HomePage() {
  return <main>
    <section className="relative overflow-hidden px-5 pb-20 pt-8 sm:px-8 sm:pb-28 sm:pt-14 lg:px-10 lg:pb-36 lg:pt-20">
      <div className="pointer-events-none absolute left-[-12rem] top-[-14rem] size-[34rem] rounded-full bg-[#e7eafe] opacity-70 blur-3xl" />
      <div className="relative mx-auto grid max-w-[1280px] items-center gap-14 lg:grid-cols-[.9fr_1.1fr] lg:gap-16">
        <Reveal>
          <Eyebrow>One calm system for changing costs</Eyebrow>
          <h1 className="max-w-[690px] font-[family-name:var(--font-display)] text-[clamp(3.5rem,7.2vw,6.7rem)] font-750 leading-[.94] tracking-[-.07em] text-[#0c0f14]">Stop losing money after you buy.</h1>
          <p className="mt-7 max-w-xl text-lg leading-8 text-[#5d6673] sm:text-xl">SpendGuard watches your purchases, subscriptions and renewals so you can catch price drops, plan changes and costly renewals before they cost you more.</p>
          <div className="mt-9 flex flex-wrap items-center gap-3"><ButtonLink href="/demo">Try the demo <span aria-hidden="true">↗</span></ButtonLink><ButtonLink href="/how-it-works" variant="secondary">See how it works</ButtonLink></div>
          <p className="mt-5 text-xs text-[#818b99]">Interactive demo · no bank connection · sample data clearly labelled</p>
        </Reveal>
        <Reveal className="lg:translate-y-5"><MonitorPreview /></Reveal>
      </div>
    </section>

    <section className="border-y border-[#e1e5ea] bg-white/65"><div className="mx-auto grid max-w-[1280px] grid-cols-2 divide-x divide-y divide-[#e1e5ea] sm:grid-cols-4 sm:divide-y-0">{valueStrip.map((item, index) => <div key={item} className="flex min-h-20 items-center gap-3 px-5 py-5 text-sm font-semibold text-[#3f4854] sm:px-7"><span className="font-mono text-xs text-[#6875f5]">0{index + 1}</span>{item}</div>)}</div></section>

    <section className="px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto max-w-[1280px]"><SectionIntro eyebrow="The monitoring loop" title="Every tracked item follows one simple path." description="Establish a baseline, watch for a meaningful change, understand the impact, then decide what deserves your attention." /><div className="mt-16 grid gap-5 md:grid-cols-3">{[['01', 'Add what you buy', 'Save a purchase or subscription with the details that matter: price, terms and the next date.'], ['02', 'SpendGuard watches it', 'The monitor compares your baseline with the price, plan and renewal information you see now.'], ['03', 'Act when something changes', 'Get a plain-language alert with the amount at stake and a clear next step, never a vague notification.']].map(([number, title, text], index) => <Reveal key={number} className={`rounded-[28px] border border-[#e1e5ea] bg-white p-6 sm:p-8 ${index === 1 ? 'md:translate-y-8' : ''}`}><span className="font-mono text-sm text-[#6875f5]">{number}</span><h3 className="mt-16 font-[family-name:var(--font-display)] text-2xl font-700 tracking-[-.04em]">{title}</h3><p className="mt-4 text-sm leading-7 text-[#5d6673]">{text}</p></Reveal>)}</div></div></section>

    <section className="bg-[#101a2a] px-5 py-24 text-white sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto max-w-[1280px]"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><SectionIntro light eyebrow="PriceClaim · PlanGuard · RenewalAudit" title="One watchdog. Three ways money slips away." description="The product is unified by the decision it helps you make: what changed, what it costs and whether it deserves action." /><div className="flex justify-start lg:justify-end"><ButtonLink href="/how-it-works" variant="light">See the full system <span aria-hidden="true">↗</span></ButtonLink></div></div><div className="mt-16 grid gap-4 lg:grid-cols-3">{productSignals.map((signal, index) => <Reveal key={signal.eyebrow} className={`rounded-[24px] border border-[#283241] bg-[#131922] p-6 sm:p-7 ${index === 1 ? 'lg:translate-y-6' : ''}`}><p className="text-[10px] font-bold tracking-[.16em] text-[#8792ff]">{signal.eyebrow}</p><h3 className="mt-8 max-w-xs font-[family-name:var(--font-display)] text-2xl font-700 leading-tight tracking-[-.045em]">{signal.title}</h3><p className="mt-4 text-sm leading-6 text-[#aab3c0]">{signal.description}</p><div className="mt-8 flex items-end justify-between border-t border-[#283241] pt-5"><div><p className="text-[11px] text-[#788492]">{signal.label}</p><p className="mt-1 text-2xl font-bold text-[#cfe3f5]">{signal.value}</p></div><p className="text-right text-[11px] leading-5 text-[#aab3c0]">{signal.meta}</p></div></Reveal>)}</div></div></section>

    <section className="px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto max-w-[1280px]"><div className="grid gap-14 lg:grid-cols-[.65fr_1.35fr] lg:items-center"><SectionIntro eyebrow="See the full picture" title="A quieter way to keep an eye on your money." description="The overview turns scattered changes into one calm, prioritised view. No banking dashboard, no endless spreadsheet, no noise for its own sake." /><Reveal><MonitorPreview compact /></Reveal></div><div className="mt-16 grid gap-5 md:grid-cols-3"><div className="rounded-[24px] bg-[#e8edf4] p-6 sm:p-8"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#6875f5]">Baseline</p><p className="mt-10 font-[family-name:var(--font-display)] text-4xl font-700 tracking-[-.06em]">$349</p><p className="mt-2 text-sm text-[#5d6673]">What you paid, with context.</p></div><div className="rounded-[24px] border border-[#e1e5ea] bg-white p-6 sm:p-8"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#6875f5]">Signal</p><p className="mt-10 font-[family-name:var(--font-display)] text-4xl font-700 tracking-[-.06em]">−$50</p><p className="mt-2 text-sm text-[#5d6673]">A change worth reviewing.</p></div><div className="rounded-[24px] bg-[#e7eafe] p-6 sm:p-8"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#6875f5]">Next action</p><p className="mt-10 font-[family-name:var(--font-display)] text-4xl font-700 tracking-[-.06em]">4 days</p><p className="mt-2 text-sm text-[#5d6673]">A clear window to decide.</p></div></div></div></section>

    <section className="bg-[#0c1016] px-5 py-24 text-white sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><SectionIntro light eyebrow="Potential impact" title="The useful number is the one that changes your decision." description="SpendGuard puts price differences and annual impact into context, so a notification becomes something you can act on." /><SavingsChart /></div></section>

    <section className="px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto max-w-[1280px]"><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><SectionIntro eyebrow="Built around the moments that matter" title="Enough signal to make a better call." /><ButtonLink href="/how-it-works" variant="secondary">How it works <span aria-hidden="true">↗</span></ButtonLink></div><div className="mt-14 grid gap-px overflow-hidden rounded-[28px] border border-[#e1e5ea] bg-[#e1e5ea] sm:grid-cols-2 lg:grid-cols-3">{[['01', 'Price monitoring', 'Catch a lower price while the opportunity is still relevant.'], ['02', 'Plan history', 'Compare what you bought with what your plan became.'], ['03', 'Renewal warnings', 'See the next charge and annual impact before it lands.'], ['04', 'Unified alerts', 'One prioritised stream for purchases, plans and renewals.'], ['05', 'Historical snapshots', 'Keep a reliable baseline instead of relying on memory.'], ['06', 'Claim guidance', 'Get a plain-language checklist, never a false promise.']].map(([n, title, text]) => <div key={n} className="bg-[#f6f6f3] p-6 transition hover:bg-white sm:p-8"><span className="font-mono text-xs text-[#6875f5]">{n}</span><h3 className="mt-12 font-[family-name:var(--font-display)] text-xl font-700 tracking-[-.035em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#5d6673]">{text}</p></div>)}</div></div></section>

    <section className="px-5 pb-24 sm:px-8 sm:pb-32 lg:px-10"><div className="mx-auto max-w-[1280px] rounded-[28px] bg-[#6875f5] px-6 py-14 text-white sm:px-12 sm:py-20 lg:px-16"><div className="grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><Eyebrow light>Interactive demo</Eyebrow><h2 className="max-w-3xl font-[family-name:var(--font-display)] text-4xl font-700 leading-[1.02] tracking-[-.055em] sm:text-6xl">See what SpendGuard catches.</h2><p className="mt-5 max-w-xl text-base leading-7 text-[#eef0ff]">Open a seeded account and explore the moments where a little context can protect a lot of money.</p></div><ButtonLink href="/demo" variant="light">Try the demo <span aria-hidden="true">↗</span></ButtonLink></div></div></section>

    <section className="border-t border-[#e1e5ea] px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto max-w-[1280px]"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><SectionIntro eyebrow="From the field notes" title="Useful thinking for the costs that change quietly." description="No hype, no fake savings claims. Just practical ways to inspect the prices and plans you already pay for." /><div className="grid gap-4 sm:grid-cols-2">{resources.slice(0, 4).map(resource => <a href={`/resources/${resource.slug}`} key={resource.slug} className="group rounded-[20px] border border-[#e1e5ea] bg-white p-5 transition hover:-translate-y-1 hover:border-[#b4bcf8] hover:shadow-[0_12px_36px_rgba(12,15,20,.08)]"><div className={`h-24 rounded-2xl bg-gradient-to-br ${resource.accent}`} /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.14em] text-[#6875f5]">{resource.category}</p><h3 className="mt-2 font-[family-name:var(--font-display)] text-lg font-700 leading-tight tracking-[-.03em] group-hover:text-[#5967e8]">{resource.title}</h3><p className="mt-3 text-xs leading-5 text-[#5d6673]">{resource.readTime}</p></a>)}</div></div></div></section>

    <section className="px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto grid max-w-[1100px] gap-14 lg:grid-cols-[.7fr_1.3fr]"><SectionIntro eyebrow="Questions, answered" title="Clear about what V1 can do." description="The demo is honest by design. Explore the product without pretending the hard parts are already automated." /><FaqAccordion items={faqItems.slice(0, 4)} /></div></section>

    <section className="px-5 pb-28 sm:px-8 sm:pb-40 lg:px-10"><div className="mx-auto max-w-[1280px] overflow-hidden rounded-[28px] bg-[#e8edf4] px-6 py-14 sm:px-12 sm:py-20 lg:px-16"><div className="max-w-3xl"><Eyebrow>The money is already yours</Eyebrow><h2 className="font-[family-name:var(--font-display)] text-4xl font-700 leading-[1.02] tracking-[-.055em] sm:text-6xl">Stop letting it disappear quietly.</h2><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/signup">Start watching <span aria-hidden="true">↗</span></ButtonLink><ButtonLink href="/pricing" variant="secondary">View pricing</ButtonLink></div></div></div></section>
  </main>
}
