import { ButtonLink, Eyebrow, SectionIntro } from '@/components/marketing/marketing-ui'
import { MonitorPreview } from '@/components/marketing/product-preview'

export const metadata = { title: 'How it works' }

export default function HowItWorksPage() {
  return <main>
    <section className="px-5 pb-24 pt-14 sm:px-8 sm:pb-32 sm:pt-24 lg:px-10"><div className="mx-auto grid max-w-[1280px] gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><Eyebrow>The quiet watchtower</Eyebrow><h1 className="max-w-3xl font-[family-name:var(--font-display)] text-5xl font-750 leading-[.96] tracking-[-.07em] sm:text-7xl">Keep the baseline. Catch the change.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#5d6673]">SpendGuard makes the costs that quietly move after you buy visible, comparable and easier to act on.</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="/demo">Open the demo <span aria-hidden="true">↗</span></ButtonLink><ButtonLink href="/pricing" variant="secondary">See pricing</ButtonLink></div></div><div className="lg:translate-y-8"><MonitorPreview compact /></div></div></section>
    <section className="border-y border-[#e1e5ea] bg-white px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto max-w-[1280px]"><SectionIntro eyebrow="One monitoring engine" title="Three signals, one decision path." description="PriceClaim, PlanGuard and RenewalAudit share the same rhythm: baseline, change, impact, action." /><div className="mt-16 grid gap-6 lg:grid-cols-3">{[['01', 'PriceClaim', 'Track a purchase after checkout.', 'Keep what you paid beside the current price. When a meaningful drop appears, see the difference, the claim window and retailer policy prompts. SpendGuard gives you instructions, not an automatic refund promise.'], ['02', 'PlanGuard', 'Know when a subscription becomes less useful.', 'Save the original price and limits, then compare them with the plan today. Price, storage, seats, exports and included benefits all belong in the same view.'], ['03', 'RenewalAudit', 'Review a recurring charge before it lands.', 'See the previous price, upcoming price, renewal date and annual impact together. A small monthly change is easier to judge when you can see its yearly consequence.']].map(([number, title, lead, body]) => <div key={number} className="rounded-[28px] border border-[#e1e5ea] bg-[#f6f6f3] p-7 sm:p-9"><span className="font-mono text-sm text-[#6875f5]">{number}</span><h2 className="mt-14 font-[family-name:var(--font-display)] text-3xl font-700 tracking-[-.05em]">{title}</h2><p className="mt-3 text-sm font-semibold text-[#0c0f14]">{lead}</p><p className="mt-5 text-sm leading-7 text-[#5d6673]">{body}</p></div>)}</div></div></section>
    <section className="bg-[#101a2a] px-5 py-24 text-white sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto max-w-[1100px]"><SectionIntro light align="center" eyebrow="From signal to action" title="Every alert answers three questions." description="What changed? What is the financial consequence? What can you do next?" /><div className="mx-auto mt-14 grid max-w-4xl gap-4 sm:grid-cols-3">{[['01', 'The change', 'Price down, plan changed or renewal approaching.'], ['02', 'The impact', '$50 potential claim or +$180 per year, in plain language.'], ['03', 'The action', 'Instructions and choices, without pretending automation exists.']].map(([number, title, body]) => <div key={number} className="rounded-[22px] border border-[#283241] bg-[#131922] p-6"><span className="font-mono text-xs text-[#8792ff]">{number}</span><h3 className="mt-10 font-[family-name:var(--font-display)] text-xl font-700">{title}</h3><p className="mt-3 text-sm leading-6 text-[#aab3c0]">{body}</p></div>)}</div></div></section>
    <section className="px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto grid max-w-[1100px] gap-14 lg:grid-cols-2"><div><SectionIntro eyebrow="Manual-first V1" title="Useful before it is fully automated." description="The first version is deliberately simple. You add the purchase or subscription, and the demo uses realistic seeded data to show what the monitoring loop would surface." /></div><div className="space-y-4">{[['Add an item', 'Enter the price, date and plan details that establish your baseline.'], ['Review the history', 'Compare what was true when you bought with what is true now.'], ['Choose your next move', 'Review, claim, keep, change or mark it resolved. You stay in control.']].map(([title, body], index) => <div key={title} className="flex gap-5 rounded-2xl border border-[#e1e5ea] bg-white p-5"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#e7eafe] text-xs font-bold text-[#5967e8]">0{index + 1}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-[#5d6673]">{body}</p></div></div>)}</div></div></section>
    <section className="px-5 pb-28 sm:px-8 sm:pb-40 lg:px-10"><div className="mx-auto flex max-w-[1280px] flex-col items-start justify-between gap-8 rounded-[28px] bg-[#e7eafe] px-6 py-12 sm:px-12 sm:py-16 md:flex-row md:items-center"><div><Eyebrow>Ready to look closer?</Eyebrow><h2 className="max-w-2xl font-[family-name:var(--font-display)] text-4xl font-700 leading-none tracking-[-.055em] sm:text-5xl">Open a watchtower with sample data.</h2></div><ButtonLink href="/demo">Try the demo <span aria-hidden="true">↗</span></ButtonLink></div></section>
  </main>
}
