'use client'

import { useState } from 'react'
import { ButtonLink } from './marketing-ui'

export function PricingToggle() {
  const [yearly, setYearly] = useState(false)
  const plans = [
    { name: 'Free', detail: 'A clear starting point for your everyday spend.', monthly: '$0', yearly: '$0', cta: 'Try it free', features: ['5 tracked items', 'Weekly monitoring', 'Renewal alerts', 'Basic price tracking', 'Demo access'] },
    { name: 'Pro', detail: 'For people who want the full monitoring loop.', monthly: '$6', yearly: '$59', cta: 'Start with Pro', features: ['Unlimited tracked items', 'Daily monitoring', 'Plan-change detection', 'Historical snapshots', 'Advanced renewal audit', 'Priority alerts'] },
  ]
  return <div><div className="mx-auto flex w-fit items-center gap-1 rounded-full border border-[#d8dde5] bg-white p-1"><button type="button" onClick={() => setYearly(false)} aria-pressed={!yearly} className={`min-h-10 rounded-full px-4 text-sm font-semibold transition ${!yearly ? 'bg-[#0c0f14] text-white' : 'text-[#5d6673] hover:text-[#0c0f14]'}`}>Monthly</button><button type="button" onClick={() => setYearly(true)} aria-pressed={yearly} className={`min-h-10 rounded-full px-4 text-sm font-semibold transition ${yearly ? 'bg-[#0c0f14] text-white' : 'text-[#5d6673] hover:text-[#0c0f14]'}`}>Yearly <span className="ml-1 text-[10px] text-[#6875f5]">save $13</span></button></div><div className="mx-auto mt-12 grid max-w-4xl gap-5 md:grid-cols-2">{plans.map((plan, index) => <div key={plan.name} className={`relative rounded-[28px] border p-7 sm:p-9 ${index === 1 ? 'border-[#6875f5] bg-[#101a2a] text-white shadow-[0_16px_48px_rgba(12,15,20,.14)]' : 'border-[#e1e5ea] bg-white'}`}>{index === 1 && <span className="absolute right-7 top-7 rounded-full bg-[#8792ff] px-3 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-[#101a2a]">Most complete</span>}<p className={`text-[11px] font-bold uppercase tracking-[.16em] ${index === 1 ? 'text-[#8792ff]' : 'text-[#6875f5]'}`}>{plan.name}</p><h2 className="mt-4 font-[family-name:var(--font-display)] text-3xl font-700 tracking-[-.045em]">{plan.detail}</h2><div className="mt-8 flex items-baseline gap-2"><span className="font-[family-name:var(--font-display)] text-6xl font-700 tracking-[-.07em]">{yearly ? plan.yearly : plan.monthly}</span>{plan.name === 'Pro' && <span className={`text-sm ${index === 1 ? 'text-[#aab3c0]' : 'text-[#5d6673]'}`}>/{yearly ? 'year' : 'month'}</span>}</div><p className={`mt-2 text-xs ${index === 1 ? 'text-[#aab3c0]' : 'text-[#818b99]'}`}>{yearly ? 'billed annually' : 'no commitment'}</p><div className={`my-8 h-px ${index === 1 ? 'bg-[#283241]' : 'bg-[#e1e5ea]'}`} /> <ul className="space-y-3">{plan.features.map(feature => <li key={feature} className="flex gap-3 text-sm"><span className={`mt-1 grid size-4 shrink-0 place-items-center rounded-full text-[10px] ${index === 1 ? 'bg-[#8792ff] text-[#101a2a]' : 'bg-[#e7eafe] text-[#5967e8]'}`}>✓</span><span className={index === 1 ? 'text-[#f5f7fa]' : 'text-[#3f4854]'}>{feature}</span></li>)}</ul><ButtonLink href="/signup" variant={index === 1 ? 'light' : 'primary'} className="mt-9 w-full">{plan.cta} <span aria-hidden="true">↗</span></ButtonLink></div>)}</div><p className="mx-auto mt-7 max-w-xl text-center text-xs leading-5 text-[#818b99]">Pricing is a product preview. Payment processing is not connected in V1, and you will never be charged from this demo.</p></div>
}
