'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { useSpendGuardStore } from '@/lib/store/use-spendguard-store'
import { currency, filterAlerts, getAlertTypeLabel, getItem, relativeDate } from '@/lib/services'
import { EmptyState, Panel, StatusBadge } from '@/components/dashboard/product-ui'
import type { AlertPriority, AlertType } from '@/lib/types'

const priorityTone: Record<AlertPriority, 'neutral' | 'accent' | 'warning' | 'danger'> = { low: 'neutral', medium: 'accent', high: 'warning', urgent: 'danger' }
const typeTone: Record<AlertType, 'accent' | 'success' | 'warning' | 'danger'> = { price_drop: 'success', price_increase: 'warning', plan_change: 'accent', renewal_warning: 'danger' }

export function AlertList() {
  const { data, updateAlert } = useSpendGuardStore()
  const [query, setQuery] = useState('')
  const [type, setType] = useState<'all' | AlertType>('all')
  const [view, setView] = useState<'active' | 'all'>('active')
  const alerts = useMemo(() => filterAlerts(data.alerts.filter((alert) => view === 'all' || (!alert.resolved && !alert.dismissed)), query, type).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()), [data.alerts, query, type, view])
  return <>
    <div className="mb-5 flex flex-col gap-3"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search alerts</span><span className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--foreground-muted)]">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search alerts" className="h-12 w-full rounded-xl border border-[var(--border)] bg-white pl-10 pr-4 text-sm outline-none transition placeholder:text-[var(--foreground-muted)] focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]" /></label><select value={type} onChange={(event) => setType(event.target.value as typeof type)} aria-label="Filter alert type" className="h-12 rounded-xl border border-[var(--border)] bg-white px-3 text-sm font-semibold outline-none focus:border-[var(--accent)]"><option value="all">All alert types</option><option value="price_drop">Price drops</option><option value="price_increase">Price increases</option><option value="plan_change">Plan changes</option><option value="renewal_warning">Renewals</option></select></div><div className="flex gap-2"><button type="button" onClick={() => setView('active')} className={`min-h-10 rounded-full px-4 text-sm font-bold ${view === 'active' ? 'bg-[var(--surface-dark)] text-white' : 'border border-[var(--border)] bg-white text-[var(--foreground-secondary)]'}`}>Active ({data.alerts.filter((alert) => !alert.resolved && !alert.dismissed).length})</button><button type="button" onClick={() => setView('all')} className={`min-h-10 rounded-full px-4 text-sm font-bold ${view === 'all' ? 'bg-[var(--surface-dark)] text-white' : 'border border-[var(--border)] bg-white text-[var(--foreground-secondary)]'}`}>All alerts</button></div></div>
    <Panel className="p-3 sm:p-4">{alerts.length === 0 ? <EmptyState title={view === 'active' ? 'Your alerts are clear' : 'No matching alerts'} description={view === 'active' ? 'Resolved and dismissed alerts will stay in your history.' : 'Try another filter or search term.'} /> : <div className="space-y-2">{alerts.map((alert) => { const item = getItem(data, alert.itemId); return <article key={alert.id} className={`rounded-2xl border p-4 transition ${alert.resolved || alert.dismissed ? 'border-[var(--border)] bg-[var(--surface-subtle)] opacity-70' : 'border-[var(--border)] bg-white hover:border-[var(--accent)]'}`}><div className="flex flex-col gap-4 md:flex-row md:items-start"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl text-lg font-bold ${alert.type === 'price_drop' ? 'bg-[var(--success-soft)] text-[var(--success)]' : alert.type === 'price_increase' ? 'bg-[var(--warning-soft)] text-[var(--warning)]' : alert.type === 'plan_change' ? 'bg-[var(--accent-soft)] text-[var(--accent)]' : 'bg-[var(--danger-soft)] text-[var(--danger)]'}`} aria-hidden="true">{alert.type === 'price_drop' ? '↘' : alert.type === 'price_increase' ? '↗' : alert.type === 'plan_change' ? '◫' : '!'}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Link href={`/app/items/${alert.itemId}`} className="font-display text-base font-extrabold hover:text-[var(--accent)]">{alert.title}</Link><StatusBadge tone={typeTone[alert.type]}>{getAlertTypeLabel(alert.type)}</StatusBadge><StatusBadge tone={priorityTone[alert.priority]}>{alert.priority}</StatusBadge></div><p className="mt-2 text-sm leading-6 text-[var(--foreground-secondary)]">{alert.description}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-[var(--foreground-muted)]"><span>{item?.title}</span><span>{relativeDate(alert.createdAt)}</span>{alert.deadline && <span className="text-[var(--warning)]">{alert.deadline}</span>}{alert.impact ? <span className="text-[var(--success)]">Potential impact {currency(alert.impact)}</span> : null}</div></div><div className="flex shrink-0 gap-2 md:flex-col"><Link href={`/app/items/${alert.itemId}`} className="inline-flex min-h-10 items-center justify-center rounded-xl border border-[var(--border)] px-3 text-xs font-bold hover:border-[var(--accent)]">Review</Link>{!alert.resolved && !alert.dismissed && <><button type="button" onClick={() => updateAlert(alert.id, { resolved: true })} className="inline-flex min-h-10 items-center justify-center rounded-xl bg-[var(--surface-dark)] px-3 text-xs font-bold text-white hover:bg-[#1c2a40]">Resolve</button><button type="button" onClick={() => updateAlert(alert.id, { dismissed: true })} className="inline-flex min-h-10 items-center justify-center rounded-xl px-3 text-xs font-bold text-[var(--foreground-secondary)] hover:bg-[var(--surface-subtle)]">Dismiss</button></>}</div></div></article> })}</div>}</Panel>
  </>
}

