import Link from 'next/link'
import { ArrowRight, CalendarClock, ExternalLink, FileSearch } from 'lucide-react'
import { compareBaseline, formatMoney } from '@/features/afterprice/comparison'
import type { BaselineRecord } from '@/features/afterprice/types'
import { Panel, StatusBadge } from '@/components/dashboard/product-ui'

export function ComparisonCard({ record, compact = false }: { record: BaselineRecord; compact?: boolean }) {
  const comparison = compareBaseline(record); const observation = comparison.latestObservation
  const tone = comparison.kind === 'price_decrease' ? 'success' : comparison.kind === 'price_increase' || comparison.kind === 'subscription_change' ? 'warning' : comparison.kind === 'no_observation' ? 'neutral' : 'accent'
  return <Panel className="overflow-hidden"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><StatusBadge tone={tone}>{comparison.headline}</StatusBadge></div><h3 className="mt-3 font-display text-xl font-extrabold">{record.display_name}</h3><p className="mt-1 text-sm text-[var(--foreground-secondary)]">{record.entities.provider}{record.entities.variant ? ` · ${record.entities.variant}` : ''}{record.entities.size_label ? ` · ${record.entities.size_label}` : ''}</p></div>{compact && <Link href={`/app/baselines/${record.id}`} className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-[var(--accent)]">Open record <ArrowRight className="h-4 w-4" /></Link>}</div>
    <div className="mt-6 grid gap-1 rounded-xl bg-[var(--surface-subtle)] p-1 sm:grid-cols-3"><Value label="Original baseline" value={formatMoney(record.original_amount_cents)} detail={new Date(record.captured_at).toLocaleDateString('en-AU')} /><Value label="Current observation" value={comparison.currentAmountCents === null ? 'Not available' : formatMoney(comparison.currentAmountCents)} detail={observation ? new Date(observation.observed_at).toLocaleString('en-AU') : 'Waiting for evidence'} /><Value label="Change" value={comparison.amountDeltaCents === null ? 'Unknown' : comparison.amountDeltaCents === 0 ? '$0.00' : `${comparison.amountDeltaCents > 0 ? '+' : '−'}${formatMoney(Math.abs(comparison.amountDeltaCents))}`} detail={comparison.details.join(' ')} /></div>
    {!compact && <div className="mt-6 grid gap-5 lg:grid-cols-2"><div><div className="flex items-center gap-2 font-bold"><FileSearch className="h-4 w-4 text-[var(--accent)]" />Evidence</div><dl className="mt-3 space-y-3 text-sm"><Meta label="Source" value={observation?.source_name ?? 'No observation source'} /><Meta label="Observed" value={observation ? new Date(observation.observed_at).toLocaleString('en-AU') : 'Not observed'} /><Meta label="Origin" value={observation?.origin ?? 'None'} /></dl>{observation?.source_url && <Link href={observation.source_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center gap-2 text-sm font-bold text-[var(--accent)]">Open source <ExternalLink className="h-4 w-4" /></Link>}</div><div className="rounded-xl bg-[var(--signal-soft)] p-4"><div className="flex items-center gap-2 font-bold"><CalendarClock className="h-4 w-4" />Next action</div><p className="mt-2 text-sm leading-6">{comparison.nextAction.label}</p><p className="mt-3 text-xs font-semibold uppercase tracking-[0.1em] text-[var(--foreground-secondary)]">{comparison.nextAction.category}</p></div></div>}</Panel>
}
function Value({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-lg bg-[var(--surface)] p-4"><p className="text-xs font-bold uppercase tracking-[0.1em] text-[var(--foreground-muted)]">{label}</p><p className="mt-2 text-xl font-extrabold tabular-nums">{value}</p><p className="mt-2 text-xs leading-5 text-[var(--foreground-secondary)]">{detail}</p></div> }
function Meta({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-[var(--border)] pb-3"><dt className="text-[var(--foreground-secondary)]">{label}</dt><dd className="text-right font-semibold">{value}</dd></div> }
